### ISSUE TITLE
English strings end up in some non-english translation files

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-tx-translator#18] opened 2023-08-22 03:33 UTC
When running tx translator with tx_pull=1, we sometimes end up with english strings in non-english translation files.

For example in https://github.com/silverstripe/silverstripe-mfa/pull/506, we see several english strings being added to the de.js translation files. But when we look in transifex, those strings are _explicitly_ not translated for de yet, so they shouldn't be pulled through.
![silverstripe/mfa in transifex showing the untranslated strings for the "de" locale](https://github.com/silverstripe/silverstripe-tx-translator/assets/36352093/6f443dd7-af4c-4211-ae2b-0dcc2c501a15)

## Notes
I have a few thoughts about this:
- This could be a result of running `tx pull` with both `-t` and `-s` flags together - we might need to run pull twice per module, once with each flag.
- There might be a setting in transifex we need to change via the web portal.
- As a last resort, we could simply unset any values in translation files that match their en counterpart.

## PRs
- https://github.com/silverstripe/silverstripe-tx-translator/pull/19

**Comment by emteknetnz** [comment] 2023-08-31 05:20
Have confirmed locally that it's the `tx pull` step that's causing the en strings to show up in de.yml, so it's not something PHP related which would have been an easier fix

I've had a good look through transifex including on the settings page for mfa - https://app.transifex.com/silverstripe/silverstripe-mfa/settings/workflow/ and I couldn't find anything relevant

I tried change the tx command to `tx pull -a - t -f` (removing the -s) - it made no difference

I think the "As a last resort, we could simply unset any values in translation files that match their en counterpart." is a good idea.  We've probably already accidentally committed a bunch of en "translations" so makes sense to undo them.

**Comment by GuySartorelli** [comment] 2023-09-01 00:41
PR merged. I'm on the fence as to whether this should be run now (just on 4.13 and merge up) or just wait until next time the issue is created - so I'll reassign to @emteknetnz and he can decide if that's in scope or not.

**Comment by emteknetnz** [comment] 2023-09-01 05:04
Next issue is in under 3 months, I wouldn't worry about it for now, we've had far more than enough automated PR's recently :-) Practically speaking this won't make much of a difference because an erroneous english "translation" is no different from a missing translation defaulting back to english

**Closed as completed by emteknetnz** 2023-09-01 05:04 UTC
Labels: affects/v4, affects/v5, type/bug
